# GoReleaser config for present2pdf
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/present2pdf
    binary: present2pdf
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?: .+'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?: .+'
      order: 1
    - title: Documentation
      regexp: '^docs(\(.+\))?: .+'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
